<a href="https://colab.research.google.com/github/Lorenarrieta69/Code_in_class/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structure?**

DS are like variable, they *save* information. the difference is that DS can store man than 1 value.

Formally, Ds store a **sequence** of values which can be located with an index (sciling). Ex: list, vectors and matrices, databases.

Now, basic python sucks!!! its lacks specialized tools. In this cas, we nees to install `numpy`

# **2. Linear Algebra - Numpy**




## 2.1.  *What is Numpy?*

Numpy (or Numerical python) is collection of functions and methods to handle Ds

This library works very well with othe libraries and it is very popular. 

In [ ]:
# Install a library

import numpy as np



In [ ]:
np.array # Example

<function numpy.array>

## 2.2. Numpy arrays - vectors and matrices

Objects arranged by row and columns. Wiyh these object you can sum and multiply.

*Example 1*

Let $a$ be a vector with 2 rows and 1 column: 

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2} 
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**. And the dimension or shape is $(2,1)$ or $(2 \times 1)$.

*Example 2*

et $a$ be a vector with 1 rows and 2 column: 

\begin{equation}
b = \left[\begin{array}{c} b_{1} & b_{2} 
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the dimension or shape is $(1,2)$ or $(1 \times 2)$.

*Example 3*

A matrix has more tha 1 row and more than 1 column. 

Of course if the number of rows and columns are equal, it is called a *squared matrix*.

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n \times m)$.

For the case of $n=3$ and $m=3$

\begin{equation}
M = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}

Now, all os this in code.

In [ ]:
# Example - Column Vector

a = np.array([[4],[5],[6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - Matrix

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**

In [ ]:
# nr: store the number of rows
# nc: store the number of columns
nr, nc = M.shape 

**Size of DS**

In python, *Size* means yhe number of elementes in a Ds.

In [ ]:
M.size

9

In [ ]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))
z/w # se borra


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3 Slincing

it ia the same as string variable, onl with minor modifications.

Let´s see:


```
#Tiene formato de código
```



In [ ]:
# Extract the 1st element

## Column vector 

print(a[0,0])
print(type(a[0,0]))

## Row vector 

print(b[0,0])
print(type(b[0,0]))

## Matrix
print(M[1,1])


4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
# Extrac the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [ ]:
# Extract a subset

## Column Vector
print(a[0:2])

## Row Vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4. Useful methods

### Zeros and Ones

In [ ]:
# Create a row vector of a 0´s of size (7,1)

#z1 = np.array([[0,0,0,0,0,0,0]])

#Zeros

## one dimensional

z1 = np.zeros(7)
print(z1)

z2 = np.zeros(7, dtype = int)
print(z2)

# Two dimnsional 
z1 = np.zeros((4,5))
print(z1)



[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Ones

## one dimensional

o1 = np.ones(7)
print(o1)

o2 = np.ones(7, dtype = int)
print(o2)

# Two dimnsional 
o1 = np.ones((4,5))
print(o1)


[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Another creation options

In [ ]:
# Full

## One dimension
np.full(7,13)

## Two dimension
np.full((3,2),13)


array([[13, 13],
       [13, 13],
       [13, 13]])

In [ ]:
# A DS with spaced values (likes a sequence)

## A custom sequence - only can create one dimension 

np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [ ]:
## A custom sequence - starting with a and stop at b
a = 3
b = 25
np.arange(a,b)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [ ]:
## A custom se sequence with a set step
a = 3
b = 25
s = 0.25 #step
np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [ ]:
## Linear space

a = 15
b = 17
n = 10

np.linspace(a, b, num = n)

array([15.        , 15.22222222, 15.44444444, 15.66666667, 15.88888889,
       16.11111111, 16.33333333, 16.55555556, 16.77777778, 17.        ])

### Random numbers

We are talking about probabilities, and of  probabilistic distribitions.


#### Uniform distribution over [0,1)

In [ ]:
# A single vale
np.random.rand()

0.9213241241146511

In [ ]:
# Example 1 - The coin toss
## Here we are going to simulate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [ ]:
# Example 2 - Ranking

## The idea is to print 'low' if the number is lower than 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is greater than 0.7

rnd = np.random.rand()

if np.random.rand() <= 0.3:
  print('Low', rnd)
elif np.random.rand() > 0.3 and rnd <= 0.7:
  print('Average',rnd)
else: 
  print('High',rnd)

Average 0.22917277262111369


**Exercise**

Code the following game. Print the message 'You win!' if two coin tosses are heads and print 'you lose!' otherwise


In [ ]:
# Solucion 1.0

## Firt try (or attemept )

First_attemept = np.random.rand()

if First_attemept <=0.5: 
  print('Head', First_attemept)
else: 
  print('Tails', First_attemept)

## second try (or attemept )
Second_attemept = np.random.rand()

if Second_attemept <=0.5: 
  print('Head', Second_attemept)
else: 
  print('Tails', Second_attemept)

# combine result
if First_attemept <=0.5 and Second_attemept <=0.5:
  print('You win!')
else:
  print('You lose!')

Head 0.10634111185382833
Head 0.053270073123257156
You win!


In [50]:
#Solucion 2.0 

First_attemept  = np.random.rand()
Second_attemept = np.random.rand()
results         = np.array([['Head', 'Tails']])
indx1           = int(round(First_attemept,0))
indx2           = int(round(Second_attemept,0))

if First_attemept <=0.5 and Second_attemept <=0.5:
  print('Head', First_attemept)
  print('Head', Second_attemept)
  print('You win!')
else:
  print(results[0,indx1], First_attemept)
  print(results[0,indx2], Second_attemept)
  print('You lose!')

Tails 0.8996807750506651
Head 0.3678653551759512
You lose!


In [64]:
#Solucion 3.0

tries = np.random.rand(2)

results         = np.array([['Head', 'Tails']])
indx1           = int(round(tries[0],0))
indx2           = int(round(tries[1],0))

if tries[0] <=0.5 and tries[1] <=0.5:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')
else:
  print(results[0,indx1], tries[0])
  print(results[0,indx2], tries[1])
  print('You lose!')

Tails 0.6723028579882319
Head 0.4096324641768555
You lose!


In [58]:
# One dimensional array
np.random.rand(4)

array([0.15104267, 0.66432886, 0.70520249, 0.6797944 ])

In [65]:
# Two dimensional arrays
np.random.rand(7,8)

array([[0.67391975, 0.28820164, 0.62221666, 0.14340307, 0.38980246,
        0.63006897, 0.65571517, 0.62396725],
       [0.10457952, 0.10212288, 0.36637658, 0.83315235, 0.59222282,
        0.50107079, 0.12060252, 0.05576741],
       [0.06643848, 0.93993845, 0.53399029, 0.17062318, 0.61769933,
        0.08777856, 0.924335  , 0.77322343],
       [0.5421116 , 0.83233137, 0.68661792, 0.65750075, 0.59176189,
        0.74505037, 0.91265094, 0.99939137],
       [0.72068398, 0.3262138 , 0.92802882, 0.79470847, 0.15333638,
        0.22832522, 0.36193901, 0.75883181],
       [0.4850025 , 0.22678082, 0.59240679, 0.78662448, 0.11670347,
        0.86683259, 0.27187773, 0.70470842],
       [0.18531133, 0.02761599, 0.13847262, 0.54896263, 0.00429986,
        0.37351842, 0.33157919, 0.3046824 ]])

### Uniform distribution over [a,b)

In [77]:
# One value
np.random.uniform(low= 10, high = 0)

6.040949927048505

In [78]:
# One dimensional
np.random.uniform(low= 10, high = 5, size = 10)

array([4.18050853, 3.7467734 , 3.63712535, 4.74081073, 3.3067631 ,
       3.26542022, 4.54540271, 3.01469185, 3.26246037, 4.74912536])

In [80]:
# Two dimensional

np.random.uniform(low= -10, high = 0, size = (4,2))

array([[-8.17407219, -9.71287774],
       [-8.70595416, -9.29138767],
       [-7.13977512, -9.46873097],
       [-1.99083954, -8.81132045]])

## Normal Distribution

In [82]:
# Standard Normal - N ~ (0,1)
np.random.randn()
np.random.randn(8)
np.random.randn(7,5)

array([[ 0.18597496, -0.12111176, -0.70229473, -1.18091863,  0.47349726],
       [-0.42340448,  1.30433803, -0.61113317,  1.85248032, -2.37782507],
       [ 0.96864269, -0.39312897, -0.29764257, -0.92836891,  0.21416186],
       [-0.48470005,  0.38950455,  0.9550993 , -0.24210995,  0.28128877],
       [-0.43340494, -1.20745483,  1.89169634, -0.31407047,  1.15674486],
       [-0.3065046 ,  0.34491848,  0.7810925 , -0.03423166,  0.16893475],
       [-1.2926114 ,  0.03695327, -0.4879784 ,  1.03297537,  1.85602293]])

In [83]:
# Normal - N ~ (mu, sigma)

mu = 0.001 # mean
sigma = 0.1 # std. deviation

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))

array([[-0.05206566],
       [ 0.00959397],
       [-0.02780953]])

### Random Integer

In [ ]:
np.random.randint(low = 0, high = 10 ) # one value
np.random.randint(low = 0, high = 10,  size = 8 ) # one dimension
np.random.randint(low = 0, high = 10,  size = (2,3)) # Two dimensions