<a href="https://colab.research.google.com/github/Lorenarrieta69/Code_in_class/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structure?**

DS are like variable, they *save* information. the difference is that DS can store man than 1 value.

Formally, Ds store a **sequence** of values which can be located with an index (sciling). Ex: list, vectors and matrices, databases.

Now, basic python sucks!!! its lacks specialized tools. In this cas, we nees to install `numpy`

# **2. Linear Algebra - Numpy**




## 2.1.  *What is Numpy?*

Numpy (or Numerical python) is collection of functions and methods to handle Ds

This library works very well with othe libraries and it is very popular. 

In [10]:
# Install a library

import numpy as np



In [ ]:
np.array # Example

<function numpy.array>

## 2.2. Numpy arrays - vectors and matrices

Objects arranged by row and columns. Wiyh these object you can sum and multiply.

*Example 1*

Let $a$ be a vector with 2 rows and 1 column: 

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2} 
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**. And the dimension or shape is $(2,1)$ or $(2 \times 1)$.

*Example 2*

et $a$ be a vector with 1 rows and 2 column: 

\begin{equation}
b = \left[\begin{array}{c} b_{1} & b_{2} 
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the dimension or shape is $(1,2)$ or $(1 \times 2)$.

*Example 3*

A matrix has more tha 1 row and more than 1 column. 

Of course if the number of rows and columns are equal, it is called a *squared matrix*.

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n \times m)$.

For the case of $n=3$ and $m=3$

\begin{equation}
M = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}

Now, all os this in code.

In [ ]:
# Example - Column Vector

a = np.array([[4],[5],[6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [ ]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [ ]:
# Example - Matrix

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**

In [ ]:
# nr: store the number of rows
# nc: store the number of columns
nr, nc = M.shape 

**Size of DS**

In python, *Size* means yhe number of elementes in a Ds.

In [ ]:
M.size

9

In [ ]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))
z/w # se borra


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3 Slincing

it ia the same as string variable, onl with minor modifications.

Let´s see:


```
#Tiene formato de código
```



In [ ]:
# Extract the 1st element

## Column vector 

print(a[0,0])
print(type(a[0,0]))

## Row vector 

print(b[0,0])
print(type(b[0,0]))

## Matrix
print(M[1,1])


4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [ ]:
# Extrac the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [ ]:
# Extract a subset

## Column Vector
print(a[0:2])

## Row Vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]


## 2.4. Useful methods

### Zeros and Ones

In [ ]:
# Create a row vector of a 0´s of size (7,1)

#z1 = np.array([[0,0,0,0,0,0,0]])

#Zeros

## one dimensional

z1 = np.zeros(7)
print(z1)

z2 = np.zeros(7, dtype = int)
print(z2)

# Two dimnsional 
z1 = np.zeros((4,5))
print(z1)



[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Ones

## one dimensional

o1 = np.ones(7)
print(o1)

o2 = np.ones(7, dtype = int)
print(o2)

# Two dimnsional 
o1 = np.ones((4,5))
print(o1)


[1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Another creation options

In [ ]:
# Full

## One dimension
np.full(7,13)

## Two dimension
np.full((3,2),13)


array([[13, 13],
       [13, 13],
       [13, 13]])

In [ ]:
# A DS with spaced values (likes a sequence)

## A custom sequence - only can create one dimension 

np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [ ]:
## A custom sequence - starting with a and stop at b
a = 3
b = 25
np.arange(a,b)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [ ]:
## A custom se sequence with a set step
a = 3
b = 25
s = 0.25 #step
np.arange(a,b,s)

array([ 3.  ,  3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,
        5.25,  5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,
        7.5 ,  7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,
        9.75, 10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75,
       12.  , 12.25, 12.5 , 12.75, 13.  , 13.25, 13.5 , 13.75, 14.  ,
       14.25, 14.5 , 14.75, 15.  , 15.25, 15.5 , 15.75, 16.  , 16.25,
       16.5 , 16.75, 17.  , 17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 ,
       18.75, 19.  , 19.25, 19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75,
       21.  , 21.25, 21.5 , 21.75, 22.  , 22.25, 22.5 , 22.75, 23.  ,
       23.25, 23.5 , 23.75, 24.  , 24.25, 24.5 , 24.75])

In [ ]:
## Linear space

a = 15
b = 17
n = 10

np.linspace(a, b, num = n)

array([15.        , 15.22222222, 15.44444444, 15.66666667, 15.88888889,
       16.11111111, 16.33333333, 16.55555556, 16.77777778, 17.        ])

### Random numbers

We are talking about probabilities, and of  probabilistic distribitions.


#### Uniform distribution over [0,1)

In [ ]:
# A single vale
np.random.rand()

0.9213241241146511

In [ ]:
# Example 1 - The coin toss
## Here we are going to simulate a coin toss

if np.random.rand() <= 0.5:
  print('head')
else:
  print('tails')

head


In [ ]:
# Example 2 - Ranking

## The idea is to print 'low' if the number is lower than 0.3
## print 'Average' if is between 0.3 and 0.7
## print 'High' if it is greater than 0.7

rnd = np.random.rand()

if np.random.rand() <= 0.3:
  print('Low', rnd)
elif np.random.rand() > 0.3 and rnd <= 0.7:
  print('Average',rnd)
else: 
  print('High',rnd)

Average 0.22917277262111369


**Exercise**

Code the following game. Print the message 'You win!' if two coin tosses are heads and print 'you lose!' otherwise


In [ ]:
# Solucion 1.0

## Firt try (or attemept )

First_attemept = np.random.rand()

if First_attemept <=0.5: 
  print('Head', First_attemept)
else: 
  print('Tails', First_attemept)

## second try (or attemept )
Second_attemept = np.random.rand()

if Second_attemept <=0.5: 
  print('Head', Second_attemept)
else: 
  print('Tails', Second_attemept)

# combine result
if First_attemept <=0.5 and Second_attemept <=0.5:
  print('You win!')
else:
  print('You lose!')

Head 0.10634111185382833
Head 0.053270073123257156
You win!


In [ ]:
#Solucion 2.0 

First_attemept  = np.random.rand()
Second_attemept = np.random.rand()
results         = np.array([['Head', 'Tails']])
indx1           = int(round(First_attemept,0))
indx2           = int(round(Second_attemept,0))

if First_attemept <=0.5 and Second_attemept <=0.5:
  print('Head', First_attemept)
  print('Head', Second_attemept)
  print('You win!')
else:
  print(results[0,indx1], First_attemept)
  print(results[0,indx2], Second_attemept)
  print('You lose!')

Tails 0.8996807750506651
Head 0.3678653551759512
You lose!


In [ ]:
#Solucion 3.0

tries = np.random.rand(2)

results         = np.array([['Head', 'Tails']])
indx1           = int(round(tries[0],0))
indx2           = int(round(tries[1],0))

if tries[0] <=0.5 and tries[1] <=0.5:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')
else:
  print(results[0,indx1], tries[0])
  print(results[0,indx2], tries[1])
  print('You lose!')

Tails 0.6723028579882319
Head 0.4096324641768555
You lose!


In [ ]:
#Solucion 5.0

tries = np.random.randint(low = 0, high = 2, size = 2)
results         = np.array([['Head', 'Tails']])

if tries[0] == 0 and tries[1] == 0:
  print('Head', tries[0])
  print('Head', tries[1])
  print('You win!')
else:
  print(results[0,tries [0]], tries[0])
  print(results[0,tries [1]], tries[1])
  print('You lose!')

Head 0
Head 0
You win!


In [ ]:
# One dimensional array
np.random.rand(4)

array([0.88293707, 0.59263816, 0.834794  , 0.58400791])

In [ ]:
# Two dimensional arrays
np.random.rand(7,8)

array([[0.74488766, 0.95174775, 0.92793503, 0.37577767, 0.17825119,
        0.74613613, 0.24991364, 0.16674843],
       [0.79963687, 0.25294959, 0.94179386, 0.34126025, 0.86080863,
        0.37263418, 0.68915753, 0.79842512],
       [0.69057583, 0.34507934, 0.60457566, 0.17850199, 0.15099372,
        0.6728886 , 0.35872266, 0.85929787],
       [0.17164703, 0.23030996, 0.82640335, 0.62508799, 0.18622951,
        0.35855141, 0.41883155, 0.01950414],
       [0.28171405, 0.44607824, 0.18492817, 0.17845063, 0.89281089,
        0.48491939, 0.28133995, 0.52397197],
       [0.69072692, 0.9715884 , 0.71333227, 0.29917611, 0.99362065,
        0.46653799, 0.82734795, 0.2091594 ],
       [0.90833832, 0.49643183, 0.37529809, 0.78890766, 0.09793003,
        0.17697382, 0.49615238, 0.29365089]])

### Uniform distribution over [a,b)

In [11]:
# One value
np.random.uniform(low= 10, high = 0)

1.8405834618865633

In [12]:
# One dimensional
np.random.uniform(low= 10, high = 5, size = 10)

array([9.59729191, 7.28877275, 7.05955667, 9.18509363, 8.80946427,
       7.58459335, 9.68984264, 9.62661486, 9.11983095, 9.15203536])

In [13]:
# Two dimensional

np.random.uniform(low= -10, high = 0, size = (4,2))

array([[-5.4652705 , -6.28074787],
       [-3.91822126, -0.34492608],
       [-9.98870629, -6.18733338],
       [-6.54364761, -5.66018536]])

## Normal Distribution

In [14]:
# Standard Normal - N ~ (0,1)
np.random.randn()
np.random.randn(8)
np.random.randn(7,5)

array([[-1.74832671, -0.73421985, -0.31139937, -0.60760967, -0.58885695],
       [-0.1728494 ,  0.37679082,  0.28896461,  0.37413045, -0.13000601],
       [-0.81288265,  0.00904567,  0.67677152, -0.0665964 , -1.60144922],
       [-2.47688019, -0.43627051,  0.01622653, -0.14275853, -0.15310905],
       [ 0.17278691,  0.93806077, -0.34495467, -0.36144353, -0.17174831],
       [-2.41498447, -0.21117612,  0.11572389, -0.03798494,  0.17773154],
       [ 1.96879269,  0.39389645, -1.09326198, -0.35470831, -0.22640174]])

In [15]:
# Normal - N ~ (mu, sigma)

mu = 0.001 # mean
sigma = 0.1 # std. deviation

np.random.normal(mu, sigma)
np.random.normal(mu, sigma, size = 5)
np.random.normal(mu, sigma, size = (3,1))

array([[ 0.00793116],
       [ 0.02722944],
       [-0.18428777]])

### Random Integer

In [16]:
np.random.randint(low = 0, high = 10 ) # one value
np.random.randint(low = 0, high = 10,  size = 8 ) # one dimension
np.random.randint(low = 0, high = 10,  size = (2,3)) # Two dimensions

array([[8, 6, 7],
       [3, 4, 1]])

Exercise 1 

**Roulette!**

Let's simulate a casino game. Specifically, a single-Zero (french) roulette.

This game consists on rolling a ball over a wheel with number pockets.

Game
To keep it simple, you can bet on a number a bet on a color.

Create the corresponding code to simulate a round. You must show what was yoy bet (number and color) and the actual resul.

*Tip*

To determine if a number (In int format) is even or odd, you can use:

In [47]:
tries = np.random.randint(low = 0, high = 37)
Bet = 2
print('Results:', tries)
print('Bet:', Bet)

'You win!' if (tries == Bet) else 'You lose!'


tries = np.random.randint(low = 0, high = 37)
Bet = Numbers_Red

Number_White = [0]
Numbers_Black = [1,3,5,7,9,12,14,16,18,20,21,23,25,27,29,31,32,34,36]
Numbers_Red = [2,4,6,8,10,11,13,15,17,19,22,24,26,28,30,33,35]

print('Results:', tries)
print('Bet:', Bet)

'You win!' if (tries == Bet) else 'You lose!'




Results: 7
Bet: 2
Results: 35
Bet: [2, 4, 6, 8, 10, 11, 13, 15, 17, 19, 22, 24, 26, 28, 30, 33, 35]


'You lose!'

In [18]:
number = 25 # Example 

'even' if (number % 2) == 0 else 'Odd'

'Odd'

In [36]:
tries = np.random.randint(low = 0, high = 37)
Bet = 24

print('Results:', tries)
print('Bet:', Bet)

'You win!' if (tries == Bet) else 'You lose!'



Results: 29
Bet: 24
Results: 22
Bet: [2, 4, 6, 8, 10, 11, 13, 15, 17, 19, 22, 24, 26, 28, 30, 33, 35]


'You lose!'

In [20]:
tries = np.random.randint(low = 0, high = 37)
White =[0]
'Black' if (tries % 2) == 0 else 'Red'
 





'Black'

In [44]:
tries = np.random.randint(low = 0, high = 37)
Bet = Numbers_Red

Number_White = [0]
Numbers_Black = [1,3,5,7,9,12,14,16,18,20,21,23,25,27,29,31,32,34,36]
Numbers_Red = [2,4,6,8,10,11,13,15,17,19,22,24,26,28,30,33,35]

print('Results:', tries)
print('Bet:', Bet)

'You win!' if (tries == Bet) else 'You lose!'

 

Results: 22
Bet: [2, 4, 6, 8, 10, 11, 13, 15, 17, 19, 22, 24, 26, 28, 30, 33, 35]


'You lose!'