<a href="https://colab.research.google.com/github/Lorenarrieta69/Code_in_class/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a data structure?**

DS are like variable, they *save* information. the difference is that DS can store man than 1 value.

Formally, Ds store a **sequence** of values which can be located with an index (sciling). Ex: list, vectors and matrices, databases.

Now, basic python sucks!!! its lacks specialized tools. In this cas, we nees to install `numpy`

# **2. Linear Algebra - Numpy**




## 2.1.  *What is Numpy?*

Numpy (or Numerical python) is collection of functions and methods to handle Ds

This library works very well with othe libraries and it is very popular. 

In [5]:
# Install a library

import numpy as np



In [6]:
np.array # Example

<function numpy.array>

## 2.2. Numpy arrays - vectors and matrices

Objects arranged by row and columns. Wiyh these object you can sum and multiply.

*Example 1*

Let $a$ be a vector with 2 rows and 1 column: 

\begin{equation}
a = \left[\begin{array}{c} a_{1} \\ a_{2} 
    \end{array}\right]
\end{equation}

This is called a **COLUMN VECTOR**. And the dimension or shape is $(2,1)$ or $(2 \times 1)$.

*Example 2*

et $a$ be a vector with 1 rows and 2 column: 

\begin{equation}
b = \left[\begin{array}{c} b_{1} & b_{2} 
    \end{array}\right]
\end{equation}

This is called a **ROW VECTOR**. And the dimension or shape is $(1,2)$ or $(1 \times 2)$.

*Example 3*

A matrix has more tha 1 row and more than 1 column. 

Of course if the number of rows and columns are equal, it is called a *squared matrix*.

In general, let $M$ be a matrix of dimensions $(n,m)$ or $(n \times m)$.

For the case of $n=3$ and $m=3$

\begin{equation}
M = \left[\begin{array}{c} 
m_{1,1} & m_{1,2} & m_{1,3} \\
m_{2,1} & m_{2,2} & m_{2,3} \\
m_{3,1} & m_{3,2} & m_{3,3} \\
    \end{array}\right]
\end{equation}

Now, all os this in code.

In [8]:
# Example - Column Vector

a = np.array([[4],[5],[6]])
print(a)
print(a.shape)

[[4]
 [5]
 [6]]
(3, 1)


In [9]:
# Example - Row Vector

b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


In [11]:
# Example - Matrix

M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(M)
print(M.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


**A nice trick**

In [12]:
# nr: store the number of rows
# nc: store the number of columns
nr, nc = M.shape 

**Size of DS**

In python, *Size* means yhe number of elementes in a Ds.

In [14]:
M.size

9

In [22]:
# ONE WARNING

z = 2
w = np.array([[2]])
print(type(z),type(w))
z/w # se borra


<class 'int'> <class 'numpy.ndarray'>


array([[1.]])

## 2.3 Slincing

it ia the same as string variable, onl with minor modifications.

Let´s see:


```
# Tiene formato de código
```



In [30]:
# Extract the 1st element

## Column vector 

print(a[0,0])
print(type(a[0,0]))

## Row vector 

print(b[0,0])
print(type(b[0,0]))

## Matrix
print(M[1,1])


4
<class 'numpy.int64'>
1
<class 'numpy.int64'>
5


In [33]:
# Extrac the last element

print('The last element of a row vector:', b[0,-1])
print('The last element of a column vector:', a[-1,0])
print('The last element of a matrix:', M[-1,-1])

The last element of a row vector: 3
The last element of a column vector: 6
The last element of a matrix: 9


In [37]:
# Extract a subset

## Column Vector
print(a[0:2])

## Row Vector
print(b[0,0:2])

## Matrix
print(M[0:2,0:2])

[[4]
 [5]]
[1 2]
[[1 2]
 [4 5]]
